import mysql.connector

mysql = mysql.connector.connect(host = "localhost", user = "root", passwd = "")
mycursor=mysql.cursor()

mycursor.execute("create database if not exists TNS")
mycursor.execute("use TNS")
mycursor.execute("drop tables if exists loginpage1")
mycursor.execute("drop tables if exists loginpage2")
mycursor.execute("drop tables if exists soldier")
mycursor.execute("drop tables if exists weapons")
mycursor.execute("drop tables if exists vehicles")




mycursor.execute("create table if not exists soldier(RollNo char(3), Full_Name char(90), Position char(90), Phone_Number char(90), City char(90), State char(90), Age  char(90))")
mycursor.execute("create table if not exists weapons(S_no char(3), weapon_name char(90), Manufactured_by char(90), numbers char(90), bullet_size char(90), Type_of_weapons char(90))")
mycursor.execute("create table if not exists vehicles(S_no char(90), vehicle_name char(90), manufactured_by char(90), numbers char(90), weight char(90), type_of_vehicle char(90), purpose char(90))")
mycursor.execute("create table if not exists team(RollNo char(3), Full_Name char(90), Position char(90), Phone_Number char(90), City char(90), State char(90), Age  char(90))")
mycursor.execute("create table if not exists teamA(RollNo char(3), Full_Name char(90), Position char(90), Phone_Number char(90), City char(90), State char(90), Age  char(90))")
mycursor.execute("create table if not exists teamC(RollNo char(3), Full_Name char(90), Position char(90), Phone_Number char(90), City char(90), State char(90), Age  char(90))")

mycursor.execute("create table if not exists teamB(RollNo char(3), Full_Name char(90), Position char(90), Phone_Number char(90), City char(90), State char(90), Age  char(90))")
mycursor.execute("create table if not exists weapon_tean(S_no char(3), weapon_name char(90), Manufactured_by char(90), numbers char(90), bullet_size char(90), Type_of_weapons char(90))")
mycursor.execute("create table if not exists weapon_teanA(S_no char(3), weapon_name char(90), Manufactured_by char(90), numbers char(90), bullet_size char(90), Type_of_weapons char(90))")
mycursor.execute("create table if not exists weapon_teanB(S_no char(3), weapon_name char(90), Manufactured_by char(90), numbers char(90), bullet_size char(90), Type_of_weapons char(90))")
mycursor.execute("create table if not exists vehicle_teamA(S_no char(90), vehicle_name char(90), manufactured_by char(90), numbers char(90), weight char(90), type_of_vehicle char(90), purpose char(90))")
mycursor.execute("create table if not exists vehicle_teamB(S_no char(90), vehicle_name char(90), manufactured_by char(90), numbers char(90), weight char(90), type_of_vehicle char(90), purpose char(90))")
mycursor.execute("create table if not exists vehicle_team(S_no char(90), vehicle_name char(90), manufactured_by char(90), numbers char(90), weight char(90), type_of_vehicle char(90), purpose char(90))")
mycursor.execute("create table if not exists leaved(RollNo char(90), name char(90), absence char(90), going date, coming date, place char(90), purpose char(90))")
mycursor.execute("Create table if not exists loginpage1(username varchar(20), password varchar(30))")
mycursor.execute("Create table if not exists loginpage2(username varchar(20), password varchar(30))")

mycursor.execute("insert into loginpage2 values('Ken', 'KT')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Shagnik', 'SB')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Nikhil', 'NS')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Soham', 'SK')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Shaunak', 'SA')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Sudeep', 'SS')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Steve', 'SW')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Mrinal', 'MP')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Tushar', 'TH')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Niranjan', 'NR')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Anmol', 'AN')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Druva', 'DM')")
mysql.commit()
mycursor.execute("insert into loginpage2 values('Aditya', 'AH')")
mysql.commit()
mycursor.execute("insert into loginpage1 values('Shitikala', 'SH')")
mysql.commit()
mycursor.execute("insert into loginpage1 values('Sherin', 'SE')")
mysql.commit()
mycursor.execute("insert into loginpage1 values('Nageshwar', 'NRP')")
mysql.commit()
mycursor.execute("insert into loginpage1 values('Punitha', 'PB')")
mysql.commit()
mycursor.execute("insert into loginpage1 values('Ravishankar', 'RG')")
mysql.commit()
mycursor.execute("insert into weapons values('001', 'Pistol Auto 9mm', 'Canada and India', '100', '9x19 mm Parabellum', 'Semi-automatic pistol')")
mysql.commit()
mycursor.execute("insert into weapons values('002', 'SIG Sauer P226', 'Germany', '100', '9x19 mm parabellum', 'Semi-automatic pistol')")
mysql.commit()
mycursor.execute("insert into weapons values('003', 'Glock 19', 'Austria', '100', '9x19 mm parabellum', 'Semi-automatic pistol')")
mysql.commit()
mycursor.execute("insert into weapons values('004', 'Franchi SPAS-15', 'Italy', '100', '18.5x76 mm NATO', 'Combat chotgun')")
mysql.commit
mycursor.execute("insert into weapons values('005', 'OFB pump action shotgun', 'India', '100', '12 gauge', 'Pump shotgun')")
mysql.commit()
mycursor.execute("insert into weapons values('006', 'SAF carbine 2A1', 'India & UK', '100', '9x19 mm parabellum', 'Sub machine gun')")
mysql.commit()
mycursor.execute("insert into weapons values('007', 'Micro-UZI', 'Israel', '100', '9x19 mm parabellum', 'Sub machine gun')")
mysql.commit()
mycursor.execute("insert into weapons values('008', 'Steyr SSG 69', 'Austria', '100', '7.62x51 mm NATO', 'Sniper rifle')")
mysql.commit()
mycursor.execute("insert into weapons values('009', 'M249', 'Belgium & USA', '100', '5.56x45 mm NATO', 'Lightmachine gun')")
mysql.commit()
mycursor.execute("insert into weapons values('010', 'INSAS LMG', 'India', '100', '5.56x45 mm NATO', 'Assault rifle')")
mysql.commit()
#---------------------------------------------------------------------------------------------------------------------------------------------------------
mycursor.execute("insert into vehicles values('001', 'Royal Enfield Bullet 350/500', 'India', '100', '100 g', 'Motorcycle', 'Used by corps and acrobatic team')")
mysql.commit()
mycursor.execute("insert into vehicles values('002', 'Hindustan Ambassador', 'India', '100', '100g', 'Staff Car', 'Assigned to commanding officers')")
mysql.commit()
mycursor.execute("insert into vehicles values('003', 'Mahindra scorpio', 'India', '100', '100 g', 'Staff car', 'Used to ferry senior officials')")
mysql.commit()
mycursor.execute("insert into vehicles values('004', 'Tata Safari Storme 4x4', 'India', '100', '100 g', 'Light Utility Vehicle', 'To replace maruti gypsy')")
mysql.commit()
mycursor.execute("insert into vehicles values('005', 'Tata Sumo 4x4', 'India', '100', '100 g', 'Multi Utility Vehicle', 'Assigned to be a troop carrier')")
mysql.commit()
mycursor.execute("insert into vehicles values('006', 'Maruti Suzuki SX4', 'India', '100', '100 g', 'Mid Size sedan', 'Assigned to transport staff of the army')")
mysql.commit()
mycursor.execute("insert into vehicles values('007', 'Mahindra Bolero', 'India', '100', '100 g', 'Multi Utility Vehicle', 'Assigned as a staff car and troop carrier')")
mysql.commit()
mycursor.execute("insert into vehicles values('008', 'Maruti Gypsy', 'India', '100', '100 g', 'Light Utility Vehicle', 'To be replaced by Tata Safari Storme')")
mysql.commit()
mycursor.execute("insert into vehicles values('009', 'Mahindra 550 DXB', 'India', '100', '100 g', 'Light Utility Vehicle', 'Assigned to transport troops')")
mysql.commit()
mycursor.execute("insert into vehicles values('010', 'Force Gurkha 4x4', 'India', '100', '100 g', 'Light Strike Vehicle', 'Assigned to transport troops')")
mysql.commit()
mycursor.execute("insert into vehicles values('011', 'Tata LPTA 713 TC', 'India', '100', '100 g', 'Medium 4x4 truck', 'Assigned to transport troops')")
mysql.commit()
mycursor.execute("insert into vehicles values('012', 'Ashok Leyland Stallion Mk III/Mk IV', 'India', '100', '100 g', 'Medium 4x4 6x6 truck', 'Assigned to transport troops')")
mysql.commit()
mycursor.execute("insert into vehicles values('013', 'Tata LPTA 2038 HMV', 'India', '100', '100 g', '6x6 Mobility Truck', 'Assigned to transport troops')")
mysql.commit()
mycursor.execute("insert into vehicles values('014', 'BEML Tatra', 'India and Czechoslovakia', '100', '100 g', 'Heavy 4x4 trucks, 6x6 trucks, 8x8 trucks, 10x10 trucks, 12x12 trucks', 'Assigned to carry sensitive equipment')")
mysql.commit()
mycursor.execute("insert into vehicles values('015', 'Ashok Leyland Super Stallion', 'India', '100', '100 g', '6x6, 8x8, 10x10', 'Assigned to transport troops')")
mysql.commit()
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mycursor.execute("insert into soldier values('001', 'Ken Tom', 'Major', '978753845', 'Bangalore', 'Karnataka', '27')")
mysql.commit()
mycursor.execute("insert into soldier values('002', 'Shagnik', 'Colonel', '978754649', 'Bangalore', 'Karnataka', '30')")
mysql.commit()
mycursor.execute("insert into soldier values('003', 'Niggil', 'Sepoy', '969753420', 'Coimbatore', 'Tamil Nadu', '42')")
mysql.commit()
mycursor.execute("insert into soldier values('004', 'Soham', 'Naik', '988753886', 'Borivali', 'Maharashtra', '28')")
mysql.commit()
mycursor.execute("insert into soldier values('005', 'Peedus', 'Sepoy', '870753845', 'Mysore', 'Karnataka', '27')")
mysql.commit()
mycursor.execute("insert into soldier values('006', 'Brinal', 'Naik', '878053545', 'Chennai', 'Tamil Nadu', '30')")
mysql.commit()
mycursor.execute("insert into soldier values('007', 'Niranjan', 'Havildar', '868002545', 'Mumbai', 'Maharashtra', '38')")
mysql.commit()
mycursor.execute("insert into soldier values('008', 'Druva', 'Sepoy', '876083541', 'Itanagar', 'Himachal Pradesh', '33')")
mysql.commit()
mycursor.execute("insert into soldier values('009', 'Tushar', 'Havildar', '878023446', 'Chennai', 'Tamil Nadu', '30')")
mysql.commit()
mycursor.execute("insert into soldier values('010', 'Anmol', 'Lance naik', '978053523', 'Hyderabad', 'Telangana', '36')")
mysql.commit()
